#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [2]:
np.zeros(10, dtype=int)
# help(np.zeros)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [4]:
a = np.zeros(10, dtype=int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [5]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [6]:
np.arange(0, 51)[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [8]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4], dtype=int64),)

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [9]:
np.random.randint(1, 21, size=27).reshape(3,3,3)

array([[[ 1, 14, 13],
        [13, 18, 16],
        [18, 15,  8]],

       [[10, 11,  1],
        [18, 13,  6],
        [15, 17, 18]],

       [[16, 20, 15],
        [ 1,  1, 16],
        [18,  3,  3]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [10]:
arr = np.random.rand(10, 10)
print(arr)
print("max:", np.amax(arr))
print("min:",np.amin(arr))

[[0.37651666 0.9251675  0.96500109 0.39161252 0.44872901 0.65246107
  0.06582988 0.729987   0.29585076 0.77961641]
 [0.54316516 0.63342659 0.19796462 0.18463384 0.91651649 0.54529587
  0.13731339 0.47299761 0.95430995 0.12371958]
 [0.19118429 0.24101713 0.6560932  0.18128825 0.62434915 0.77731366
  0.57556239 0.52771357 0.6563903  0.39310279]
 [0.90186199 0.64521462 0.02615983 0.71186402 0.2871159  0.52183671
  0.89959353 0.13659856 0.90853781 0.71036023]
 [0.22298855 0.50901898 0.39603692 0.58954927 0.27436819 0.90771576
  0.30867152 0.68042992 0.58573854 0.15974176]
 [0.76023743 0.11066924 0.19121294 0.43788449 0.42481984 0.51698726
  0.12785272 0.93775988 0.27832036 0.24483297]
 [0.19399673 0.21035465 0.56652364 0.57124859 0.85126226 0.21560264
  0.16015226 0.48015592 0.88313185 0.64707677]
 [0.09080837 0.35556422 0.12891483 0.8281195  0.43992162 0.87437843
  0.70364074 0.56661675 0.23463032 0.80870315]
 [0.03380953 0.25278977 0.26482422 0.13169818 0.3564764  0.43418565
  0.87842849

#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [11]:
np.mean(np.random.rand(30))

0.4880402986678186

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [12]:
arr = np.random.randint(1, 11, 10)
result = np.where(arr > 3) and np.where(arr < 8)
print(arr)
print(arr[result])

[10  7  7  2  5  2  8  1  3  5]
[7 7 2 5 2 1 3 5]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [15]:
arr = np.random.randint(0, 10, 20)
result = np.where(arr < 5)
print(result)
print(arr)
print(arr[result] * 2)

(array([ 0,  1,  2,  3,  6, 10, 11, 13, 14, 15, 16], dtype=int64),)
[1 4 1 1 9 9 1 5 5 5 3 2 5 3 0 4 0 9 8 8]
[2 8 2 2 2 6 4 6 0 8 0]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [16]:
arr = np.array([1, 5, 6, 2, -2, 23, 45])
np.where(arr % 2 == 0)

(array([2, 3, 4], dtype=int64),)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [17]:
arr = np.arange(1,21)
result = np.where(arr % 3 == 0)
arr[result]

array([ 3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [18]:
np.random.randint(0, 5, 25).reshape(5, 5)

array([[2, 2, 1, 3, 4],
       [1, 3, 1, 1, 4],
       [4, 4, 2, 1, 1],
       [4, 2, 0, 3, 1],
       [4, 0, 3, 4, 0]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [19]:
arr = np.array([[0, 1],[2, 3]])
np.amax(arr), np.amin(arr)

(3, 0)

#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [20]:
arr =  np.array([[0, 1],[2, 3]])
print(np.amax(arr, axis=0))
print(np.amin(arr, axis=0))

[2 3]
[0 1]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [26]:
arr = np.random.randint(10, 21, 100000)
#print(arr)
np.mean(arr), np.median(arr), np.std(arr), np.var(arr)

(14.9966, 15.0, 3.164409651103978, 10.01348844)

#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])։

In [27]:
arr = np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
weights = np.random.randint(1, 5, len(arr))
np.average(arr, weights=weights)

13.62962962962963

#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [28]:
arr = np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
np.sort(arr)

array([[1, 2, 4, 6],
       [0, 1, 2, 6],
       [1, 4, 4, 9]])

#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [29]:
a = np.array([[3, 6, 7],
             [5, -3, 0]])
b = np.array([[1, 1],
              [2, 1],
              [3, -3]])
np.dot(a, b)

array([[ 36, -12],
       [ -1,   2]])